# Generated by Django 4.2.11 on 2025-12-16 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(blank=True, default="", max_length=255)),
                ("title", models.CharField(max_length=500)),
                ("link", models.URLField(max_length=2000)),
                ("description", models.TextField(blank=True, default="")),
                ("pub_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "stock",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news",
                        to="stock.stock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock News",
                "verbose_name_plural": "Stock News",
                "ordering": ["-pub_date", "-created_at"],
            },
        ),
    ]
