# Generated by Django 4.2.11 on 2025-12-16 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailVerificationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="The email address to verify",
                        max_length=254,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="6-digit verification code",
                        max_length=6,
                        verbose_name="Verification Code",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this code has been used for registration",
                        verbose_name="Is Used",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Verification Code",
                "verbose_name_plural": "Email Verification Codes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_profile_img",
                    models.TextField(
                        blank=True,
                        help_text="Base64 encoded PNG of the user's 128*128 avatar. No data-URI prefix.",
                        null=True,
                        verbose_name="avatar (Base64)",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
    ]
