# Generated by Django 4.2.11 on 2025-12-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FamousPortfolios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("portfolio_name", models.CharField(max_length=255)),
                (
                    "portfolio_img",
                    models.TextField(
                        blank=True,
                        help_text="Base64 encoded PNG of the portfolio's 128*128 avatar. No data-URI prefix.",
                        null=True,
                        verbose_name="portfolio img (Base64)",
                    ),
                ),
                ("portfolio_description", models.TextField(blank=True, null=True)),
                ("stocks", models.ManyToManyField(to="stock.stock")),
            ],
            options={
                "verbose_name": "Famous Portfolio",
                "verbose_name_plural": "Famous Portfolios",
            },
        ),
    ]
