# Generated by Django 5.0.3 on 2025-12-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('source', models.CharField(max_length=20)),
                ('index_name', models.CharField(max_length=50)),
                ('score', models.FloatField()),
                ('rating', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['date', 'index_name'], name='market_sent_date_d851aa_idx')],
                'unique_together': {('date', 'source', 'index_name')},
            },
        ),
    ]
