# Generated by Django 5.0.3 on 2025-12-16 03:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emailsubscription',
            unique_together={('user', 'email')},
        ),
        migrations.AddIndex(
            model_name='emailsubscription',
            index=models.Index(fields=['enabled'], name='core_emails_enabled_f7e121_idx'),
        ),
    ]
