# Generated by Django 5.0.3 on 2025-12-16 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_emailsubscription_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsubscription',
            name='last_panic_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailsubscription',
            name='last_state',
            field=models.CharField(default='NORMAL', max_length=32),
        ),
    ]
