# Generated by Django 5.0.3 on 2025-12-16 08:28

import core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_emailsubscription_last_panic_sent_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='holdings',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio1',
            field=models.JSONField(blank=True, default=core.models.default_portfolio1),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio2',
            field=models.JSONField(blank=True, default=core.models.default_portfolio2),
        ),
        migrations.AlterUniqueTogether(
            name='portfolio',
            unique_together={('user', 'name')},
        ),
    ]
